name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ production ]  # Trigger when you push source code to main
  pull_request:
    branches: [ production ]  # Build check for PRs
  workflow_dispatch:

# Sets permissions to push to main branch
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-check:
    # This job runs on PRs to check if the build works
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Clean Gatsby cache
        run: npx gatsby clean
        
      - name: Rebuild native dependencies
        run: npm rebuild
        
      - name: Build website
        run: GATSBY_DISABLE_FILE_WATCHER=true npm run build
        env:
          GATSBY_GA_MEASUREMENT_ID: ${{ secrets.GATSBY_GA_MEASUREMENT_ID }}

  build-and-deploy:
    # This job only runs on pushes to production branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest  # Use latest Ubuntu for better performance
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use Node 18 for better compatibility
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Clean Gatsby cache
        run: npx gatsby clean
        
      - name: Rebuild native dependencies
        run: npm rebuild
        
      - name: Build website
        run: GATSBY_DISABLE_FILE_WATCHER=true npm run build
        env:
          # Pass the secret to the build process
          GATSBY_GA_MEASUREMENT_ID: ${{ secrets.GATSBY_GA_MEASUREMENT_ID }}
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4